// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("host"),
        JAVA_SHORT.withName("port"),
        MemoryLayout.paddingLayout(6),
        RuntimeHelper.POINTER.withName("cert_config"),
        JAVA_INT.withName("max_sessions_per_connection"),
        JAVA_INT.withName("max_streams_per_session"),
        JAVA_LONG.withName("max_data_per_session"),
        JAVA_INT.withName("idle_timeout_ms"),
        JAVA_INT.withName("handshake_timeout_ms"),
        JAVA_BOOLEAN.withName("enable_0rtt"),
        JAVA_BOOLEAN.withName("enable_migration"),
        MemoryLayout.paddingLayout(6),
        RuntimeHelper.POINTER.withName("connection_validator"),
        RuntimeHelper.POINTER.withName("session_callback"),
        RuntimeHelper.POINTER.withName("user_context")
    ).withName("");
    static final VarHandle const$1 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("host"));
    static final VarHandle const$2 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("port"));
    static final VarHandle const$3 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("cert_config"));
    static final VarHandle const$4 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("max_sessions_per_connection"));
    static final VarHandle const$5 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("max_streams_per_session"));
}


