// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final VarHandle const$0 = constants$18.const$4.varHandle(MemoryLayout.PathElement.groupElement("minor"));
    static final VarHandle const$1 = constants$18.const$4.varHandle(MemoryLayout.PathElement.groupElement("patch"));
    static final VarHandle const$2 = constants$18.const$4.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "wtf_get_version",
        constants$19.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wtf_context_create",
        constants$9.const$5
    );
}


