// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("value")
    ).withName("");
    static final VarHandle const$1 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$2 = constants$2.const$0.varHandle(MemoryLayout.PathElement.groupElement("value"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("origin"),
        RuntimeHelper.POINTER.withName("path"),
        RuntimeHelper.POINTER.withName("authority"),
        RuntimeHelper.POINTER.withName("headers"),
        JAVA_LONG.withName("header_count"),
        RuntimeHelper.POINTER.withName("peer_address"),
        JAVA_LONG.withName("address_length")
    ).withName("");
    static final VarHandle const$4 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("origin"));
    static final VarHandle const$5 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("path"));
}


