// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("user_context"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffers"),
        JAVA_INT.withName("buffer_count"),
        JAVA_BOOLEAN.withName("fin"),
        MemoryLayout.paddingLayout(3)
    ).withName("");
    static final VarHandle const$2 = constants$7.const$1.varHandle(MemoryLayout.PathElement.groupElement("buffers"));
    static final VarHandle const$3 = constants$7.const$1.varHandle(MemoryLayout.PathElement.groupElement("buffer_count"));
    static final VarHandle const$4 = constants$7.const$1.varHandle(MemoryLayout.PathElement.groupElement("fin"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffers"),
        JAVA_INT.withName("buffer_count"),
        JAVA_BOOLEAN.withName("cancelled"),
        MemoryLayout.paddingLayout(3)
    ).withName("");
}


