// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final VarHandle const$0 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("authority"));
    static final VarHandle const$1 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("headers"));
    static final VarHandle const$2 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("header_count"));
    static final VarHandle const$3 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("peer_address"));
    static final VarHandle const$4 = constants$2.const$3.varHandle(MemoryLayout.PathElement.groupElement("address_length"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("session"),
        RuntimeHelper.POINTER.withName("user_context"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                JAVA_INT.withName("error_code"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("reason")
            ).withName("disconnected"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("stream"),
                JAVA_INT.withName("stream_type"),
                MemoryLayout.paddingLayout(4)
            ).withName("stream_opened"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buffers"),
                JAVA_INT.withName("buffer_count"),
                JAVA_INT.withName("state")
            ).withName("datagram_send_state_changed"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("length"),
                MemoryLayout.paddingLayout(4),
                RuntimeHelper.POINTER.withName("data")
            ).withName("datagram_received")
        ).withName("$anon$0")
    ).withName("");
}


