// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__report_gsfailure",
        constants$0.const$4
    );
    static final VarHandle const$1 = JAVA_LONG.varHandle();
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("__security_cookie", JAVA_LONG);
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("length"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("data")
    ).withName("");
    static final VarHandle const$4 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("length"));
    static final VarHandle const$5 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("data"));
}


