// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {}
    static final VarHandle const$0 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("max_data_per_session"));
    static final VarHandle const$1 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("idle_timeout_ms"));
    static final VarHandle const$2 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("handshake_timeout_ms"));
    static final VarHandle const$3 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("enable_0rtt"));
    static final VarHandle const$4 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("enable_migration"));
    static final VarHandle const$5 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("connection_validator"));
}


