// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     wtf_certificate_type_t cert_type;
 *     union  cert_data;
 *     char* principal;
 *     char* ca_cert_file;
 * };
 * }
 */
public class wtf_certificate_config_t {

    public static MemoryLayout $LAYOUT() {
        return constants$11.const$2;
    }
    public static VarHandle cert_type$VH() {
        return constants$11.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_certificate_type_t cert_type;
     * }
     */
    public static int cert_type$get(MemorySegment seg) {
        return (int)constants$11.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_certificate_type_t cert_type;
     * }
     */
    public static void cert_type$set(MemorySegment seg, int x) {
        constants$11.const$3.set(seg, x);
    }
    public static int cert_type$get(MemorySegment seg, long index) {
        return (int)constants$11.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void cert_type$set(MemorySegment seg, long index, int x) {
        constants$11.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * union {
     *     struct  file;
     *     struct  protected_file;
     *     struct  hash;
     *     struct  hash_store;
     *     struct  pkcs12;
     *     void* context;
     * };
     * }
     */
    public static final class cert_data {

        // Suppresses default constructor, ensuring non-instantiability.
        private cert_data() {}
        public static MemoryLayout $LAYOUT() {
            return constants$11.const$4;
        }
        /**
         * {@snippet :
         * struct {
         *     char* cert_path;
         *     char* key_path;
         * };
         * }
         */
        public static final class file {

            // Suppresses default constructor, ensuring non-instantiability.
            private file() {}
            public static MemoryLayout $LAYOUT() {
                return constants$11.const$5;
            }
            public static VarHandle cert_path$VH() {
                return constants$12.const$0;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* cert_path;
             * }
             */
            public static MemorySegment cert_path$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$12.const$0.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* cert_path;
             * }
             */
            public static void cert_path$set(MemorySegment seg, MemorySegment x) {
                constants$12.const$0.set(seg, x);
            }
            public static MemorySegment cert_path$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$12.const$0.get(seg.asSlice(index*sizeof()));
            }
            public static void cert_path$set(MemorySegment seg, long index, MemorySegment x) {
                constants$12.const$0.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle key_path$VH() {
                return constants$12.const$1;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* key_path;
             * }
             */
            public static MemorySegment key_path$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$12.const$1.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* key_path;
             * }
             */
            public static void key_path$set(MemorySegment seg, MemorySegment x) {
                constants$12.const$1.set(seg, x);
            }
            public static MemorySegment key_path$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$12.const$1.get(seg.asSlice(index*sizeof()));
            }
            public static void key_path$set(MemorySegment seg, long index, MemorySegment x) {
                constants$12.const$1.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment file$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        /**
         * {@snippet :
         * struct {
         *     char* cert_path;
         *     char* key_path;
         *     char* password;
         * };
         * }
         */
        public static final class protected_file {

            // Suppresses default constructor, ensuring non-instantiability.
            private protected_file() {}
            public static MemoryLayout $LAYOUT() {
                return constants$12.const$2;
            }
            public static VarHandle cert_path$VH() {
                return constants$12.const$3;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* cert_path;
             * }
             */
            public static MemorySegment cert_path$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$12.const$3.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* cert_path;
             * }
             */
            public static void cert_path$set(MemorySegment seg, MemorySegment x) {
                constants$12.const$3.set(seg, x);
            }
            public static MemorySegment cert_path$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$12.const$3.get(seg.asSlice(index*sizeof()));
            }
            public static void cert_path$set(MemorySegment seg, long index, MemorySegment x) {
                constants$12.const$3.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle key_path$VH() {
                return constants$12.const$4;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* key_path;
             * }
             */
            public static MemorySegment key_path$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$12.const$4.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* key_path;
             * }
             */
            public static void key_path$set(MemorySegment seg, MemorySegment x) {
                constants$12.const$4.set(seg, x);
            }
            public static MemorySegment key_path$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$12.const$4.get(seg.asSlice(index*sizeof()));
            }
            public static void key_path$set(MemorySegment seg, long index, MemorySegment x) {
                constants$12.const$4.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle password$VH() {
                return constants$12.const$5;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* password;
             * }
             */
            public static MemorySegment password$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$12.const$5.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* password;
             * }
             */
            public static void password$set(MemorySegment seg, MemorySegment x) {
                constants$12.const$5.set(seg, x);
            }
            public static MemorySegment password$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$12.const$5.get(seg.asSlice(index*sizeof()));
            }
            public static void password$set(MemorySegment seg, long index, MemorySegment x) {
                constants$12.const$5.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment protected_file$slice(MemorySegment seg) {
            return seg.asSlice(0, 24);
        }
        /**
         * {@snippet :
         * struct {
         *     char* thumbprint;
         * };
         * }
         */
        public static final class hash {

            // Suppresses default constructor, ensuring non-instantiability.
            private hash() {}
            public static MemoryLayout $LAYOUT() {
                return constants$13.const$0;
            }
            public static VarHandle thumbprint$VH() {
                return constants$13.const$1;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* thumbprint;
             * }
             */
            public static MemorySegment thumbprint$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$13.const$1.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* thumbprint;
             * }
             */
            public static void thumbprint$set(MemorySegment seg, MemorySegment x) {
                constants$13.const$1.set(seg, x);
            }
            public static MemorySegment thumbprint$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$13.const$1.get(seg.asSlice(index*sizeof()));
            }
            public static void thumbprint$set(MemorySegment seg, long index, MemorySegment x) {
                constants$13.const$1.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment hash$slice(MemorySegment seg) {
            return seg.asSlice(0, 8);
        }
        /**
         * {@snippet :
         * struct {
         *     char* thumbprint;
         *     char* store_name;
         * };
         * }
         */
        public static final class hash_store {

            // Suppresses default constructor, ensuring non-instantiability.
            private hash_store() {}
            public static MemoryLayout $LAYOUT() {
                return constants$13.const$2;
            }
            public static VarHandle thumbprint$VH() {
                return constants$13.const$3;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* thumbprint;
             * }
             */
            public static MemorySegment thumbprint$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$13.const$3.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* thumbprint;
             * }
             */
            public static void thumbprint$set(MemorySegment seg, MemorySegment x) {
                constants$13.const$3.set(seg, x);
            }
            public static MemorySegment thumbprint$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$13.const$3.get(seg.asSlice(index*sizeof()));
            }
            public static void thumbprint$set(MemorySegment seg, long index, MemorySegment x) {
                constants$13.const$3.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle store_name$VH() {
                return constants$13.const$4;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* store_name;
             * }
             */
            public static MemorySegment store_name$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$13.const$4.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* store_name;
             * }
             */
            public static void store_name$set(MemorySegment seg, MemorySegment x) {
                constants$13.const$4.set(seg, x);
            }
            public static MemorySegment store_name$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$13.const$4.get(seg.asSlice(index*sizeof()));
            }
            public static void store_name$set(MemorySegment seg, long index, MemorySegment x) {
                constants$13.const$4.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment hash_store$slice(MemorySegment seg) {
            return seg.asSlice(0, 16);
        }
        /**
         * {@snippet :
         * struct {
         *     void* data;
         *     size_t data_size;
         *     char* password;
         * };
         * }
         */
        public static final class pkcs12 {

            // Suppresses default constructor, ensuring non-instantiability.
            private pkcs12() {}
            public static MemoryLayout $LAYOUT() {
                return constants$13.const$5;
            }
            public static VarHandle data$VH() {
                return constants$14.const$0;
            }
            /**
             * Getter for field:
             * {@snippet :
             * void* data;
             * }
             */
            public static MemorySegment data$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$14.const$0.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * void* data;
             * }
             */
            public static void data$set(MemorySegment seg, MemorySegment x) {
                constants$14.const$0.set(seg, x);
            }
            public static MemorySegment data$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$14.const$0.get(seg.asSlice(index*sizeof()));
            }
            public static void data$set(MemorySegment seg, long index, MemorySegment x) {
                constants$14.const$0.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle data_size$VH() {
                return constants$14.const$1;
            }
            /**
             * Getter for field:
             * {@snippet :
             * size_t data_size;
             * }
             */
            public static long data_size$get(MemorySegment seg) {
                return (long)constants$14.const$1.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * size_t data_size;
             * }
             */
            public static void data_size$set(MemorySegment seg, long x) {
                constants$14.const$1.set(seg, x);
            }
            public static long data_size$get(MemorySegment seg, long index) {
                return (long)constants$14.const$1.get(seg.asSlice(index*sizeof()));
            }
            public static void data_size$set(MemorySegment seg, long index, long x) {
                constants$14.const$1.set(seg.asSlice(index*sizeof()), x);
            }
            public static VarHandle password$VH() {
                return constants$14.const$2;
            }
            /**
             * Getter for field:
             * {@snippet :
             * char* password;
             * }
             */
            public static MemorySegment password$get(MemorySegment seg) {
                return (java.lang.foreign.MemorySegment)constants$14.const$2.get(seg);
            }
            /**
             * Setter for field:
             * {@snippet :
             * char* password;
             * }
             */
            public static void password$set(MemorySegment seg, MemorySegment x) {
                constants$14.const$2.set(seg, x);
            }
            public static MemorySegment password$get(MemorySegment seg, long index) {
                return (java.lang.foreign.MemorySegment)constants$14.const$2.get(seg.asSlice(index*sizeof()));
            }
            public static void password$set(MemorySegment seg, long index, MemorySegment x) {
                constants$14.const$2.set(seg.asSlice(index*sizeof()), x);
            }
            public static long sizeof() { return $LAYOUT().byteSize(); }
            public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
            public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
            }
            public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
        }

        public static MemorySegment pkcs12$slice(MemorySegment seg) {
            return seg.asSlice(0, 24);
        }
        public static VarHandle context$VH() {
            return constants$14.const$3;
        }
        /**
         * Getter for field:
         * {@snippet :
         * void* context;
         * }
         */
        public static MemorySegment context$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$14.const$3.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * void* context;
         * }
         */
        public static void context$set(MemorySegment seg, MemorySegment x) {
            constants$14.const$3.set(seg, x);
        }
        public static MemorySegment context$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$14.const$3.get(seg.asSlice(index*sizeof()));
        }
        public static void context$set(MemorySegment seg, long index, MemorySegment x) {
            constants$14.const$3.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment cert_data$slice(MemorySegment seg) {
        return seg.asSlice(8, 24);
    }
    public static VarHandle principal$VH() {
        return constants$14.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* principal;
     * }
     */
    public static MemorySegment principal$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$14.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* principal;
     * }
     */
    public static void principal$set(MemorySegment seg, MemorySegment x) {
        constants$14.const$4.set(seg, x);
    }
    public static MemorySegment principal$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$14.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void principal$set(MemorySegment seg, long index, MemorySegment x) {
        constants$14.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle ca_cert_file$VH() {
        return constants$14.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* ca_cert_file;
     * }
     */
    public static MemorySegment ca_cert_file$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$14.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* ca_cert_file;
     * }
     */
    public static void ca_cert_file$set(MemorySegment seg, MemorySegment x) {
        constants$14.const$5.set(seg, x);
    }
    public static MemorySegment ca_cert_file$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$14.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void ca_cert_file$set(MemorySegment seg, long index, MemorySegment x) {
        constants$14.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


