// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     wtf_log_level_t log_level;
 *     wtf_log_callback_t log_callback;
 *     void* log_user_context;
 *     uint32_t worker_thread_count;
 *     _Bool enable_load_balancing;
 *     _Bool disable_encryption;
 *     wtf_execution_profile_t execution_profile;
 * };
 * }
 */
public class wtf_context_config_t {

    public static MemoryLayout $LAYOUT() {
        return constants$17.const$2;
    }
    public static VarHandle log_level$VH() {
        return constants$17.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_log_level_t log_level;
     * }
     */
    public static int log_level$get(MemorySegment seg) {
        return (int)constants$17.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_log_level_t log_level;
     * }
     */
    public static void log_level$set(MemorySegment seg, int x) {
        constants$17.const$3.set(seg, x);
    }
    public static int log_level$get(MemorySegment seg, long index) {
        return (int)constants$17.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void log_level$set(MemorySegment seg, long index, int x) {
        constants$17.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle log_callback$VH() {
        return constants$17.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_log_callback_t log_callback;
     * }
     */
    public static MemorySegment log_callback$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_log_callback_t log_callback;
     * }
     */
    public static void log_callback$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$4.set(seg, x);
    }
    public static MemorySegment log_callback$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void log_callback$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static wtf_log_callback_t log_callback(MemorySegment segment, Arena scope) {
        return wtf_log_callback_t.ofAddress(log_callback$get(segment), scope);
    }
    public static VarHandle log_user_context$VH() {
        return constants$17.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* log_user_context;
     * }
     */
    public static MemorySegment log_user_context$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* log_user_context;
     * }
     */
    public static void log_user_context$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$5.set(seg, x);
    }
    public static MemorySegment log_user_context$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void log_user_context$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle worker_thread_count$VH() {
        return constants$18.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t worker_thread_count;
     * }
     */
    public static int worker_thread_count$get(MemorySegment seg) {
        return (int)constants$18.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t worker_thread_count;
     * }
     */
    public static void worker_thread_count$set(MemorySegment seg, int x) {
        constants$18.const$0.set(seg, x);
    }
    public static int worker_thread_count$get(MemorySegment seg, long index) {
        return (int)constants$18.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void worker_thread_count$set(MemorySegment seg, long index, int x) {
        constants$18.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enable_load_balancing$VH() {
        return constants$18.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool enable_load_balancing;
     * }
     */
    public static boolean enable_load_balancing$get(MemorySegment seg) {
        return (boolean)constants$18.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool enable_load_balancing;
     * }
     */
    public static void enable_load_balancing$set(MemorySegment seg, boolean x) {
        constants$18.const$1.set(seg, x);
    }
    public static boolean enable_load_balancing$get(MemorySegment seg, long index) {
        return (boolean)constants$18.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void enable_load_balancing$set(MemorySegment seg, long index, boolean x) {
        constants$18.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle disable_encryption$VH() {
        return constants$18.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool disable_encryption;
     * }
     */
    public static boolean disable_encryption$get(MemorySegment seg) {
        return (boolean)constants$18.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool disable_encryption;
     * }
     */
    public static void disable_encryption$set(MemorySegment seg, boolean x) {
        constants$18.const$2.set(seg, x);
    }
    public static boolean disable_encryption$get(MemorySegment seg, long index) {
        return (boolean)constants$18.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void disable_encryption$set(MemorySegment seg, long index, boolean x) {
        constants$18.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle execution_profile$VH() {
        return constants$18.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_execution_profile_t execution_profile;
     * }
     */
    public static int execution_profile$get(MemorySegment seg) {
        return (int)constants$18.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_execution_profile_t execution_profile;
     * }
     */
    public static void execution_profile$set(MemorySegment seg, int x) {
        constants$18.const$3.set(seg, x);
    }
    public static int execution_profile$get(MemorySegment seg, long index) {
        return (int)constants$18.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void execution_profile$set(MemorySegment seg, long index, int x) {
        constants$18.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


