// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     char* origin;
 *     char* path;
 *     char* authority;
 *     const wtf_http_header_t* headers;
 *     size_t header_count;
 *     void* peer_address;
 *     size_t address_length;
 * };
 * }
 */
public class wtf_connection_request_t {

    public static MemoryLayout $LAYOUT() {
        return constants$2.const$3;
    }
    public static VarHandle origin$VH() {
        return constants$2.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* origin;
     * }
     */
    public static MemorySegment origin$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* origin;
     * }
     */
    public static void origin$set(MemorySegment seg, MemorySegment x) {
        constants$2.const$4.set(seg, x);
    }
    public static MemorySegment origin$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void origin$set(MemorySegment seg, long index, MemorySegment x) {
        constants$2.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle path$VH() {
        return constants$2.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* path;
     * }
     */
    public static MemorySegment path$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$2.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* path;
     * }
     */
    public static void path$set(MemorySegment seg, MemorySegment x) {
        constants$2.const$5.set(seg, x);
    }
    public static MemorySegment path$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$2.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void path$set(MemorySegment seg, long index, MemorySegment x) {
        constants$2.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle authority$VH() {
        return constants$3.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* authority;
     * }
     */
    public static MemorySegment authority$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$3.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* authority;
     * }
     */
    public static void authority$set(MemorySegment seg, MemorySegment x) {
        constants$3.const$0.set(seg, x);
    }
    public static MemorySegment authority$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$3.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void authority$set(MemorySegment seg, long index, MemorySegment x) {
        constants$3.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle headers$VH() {
        return constants$3.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * const wtf_http_header_t* headers;
     * }
     */
    public static MemorySegment headers$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$3.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * const wtf_http_header_t* headers;
     * }
     */
    public static void headers$set(MemorySegment seg, MemorySegment x) {
        constants$3.const$1.set(seg, x);
    }
    public static MemorySegment headers$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$3.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void headers$set(MemorySegment seg, long index, MemorySegment x) {
        constants$3.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle header_count$VH() {
        return constants$3.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t header_count;
     * }
     */
    public static long header_count$get(MemorySegment seg) {
        return (long)constants$3.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t header_count;
     * }
     */
    public static void header_count$set(MemorySegment seg, long x) {
        constants$3.const$2.set(seg, x);
    }
    public static long header_count$get(MemorySegment seg, long index) {
        return (long)constants$3.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void header_count$set(MemorySegment seg, long index, long x) {
        constants$3.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle peer_address$VH() {
        return constants$3.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* peer_address;
     * }
     */
    public static MemorySegment peer_address$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$3.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* peer_address;
     * }
     */
    public static void peer_address$set(MemorySegment seg, MemorySegment x) {
        constants$3.const$3.set(seg, x);
    }
    public static MemorySegment peer_address$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$3.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void peer_address$set(MemorySegment seg, long index, MemorySegment x) {
        constants$3.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle address_length$VH() {
        return constants$3.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * size_t address_length;
     * }
     */
    public static long address_length$get(MemorySegment seg) {
        return (long)constants$3.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * size_t address_length;
     * }
     */
    public static void address_length$set(MemorySegment seg, long x) {
        constants$3.const$4.set(seg, x);
    }
    public static long address_length$get(MemorySegment seg, long index) {
        return (long)constants$3.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void address_length$set(MemorySegment seg, long index, long x) {
        constants$3.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


