// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     char* host;
 *     uint16_t port;
 *     wtf_certificate_config_t* cert_config;
 *     uint32_t max_sessions_per_connection;
 *     uint32_t max_streams_per_session;
 *     uint64_t max_data_per_session;
 *     uint32_t idle_timeout_ms;
 *     uint32_t handshake_timeout_ms;
 *     _Bool enable_0rtt;
 *     _Bool enable_migration;
 *     wtf_connection_validator_t connection_validator;
 *     wtf_session_callback_t session_callback;
 *     void* user_context;
 * };
 * }
 */
public class wtf_server_config_t {

    public static MemoryLayout $LAYOUT() {
        return constants$15.const$0;
    }
    public static VarHandle host$VH() {
        return constants$15.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* host;
     * }
     */
    public static MemorySegment host$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* host;
     * }
     */
    public static void host$set(MemorySegment seg, MemorySegment x) {
        constants$15.const$1.set(seg, x);
    }
    public static MemorySegment host$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void host$set(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle port$VH() {
        return constants$15.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint16_t port;
     * }
     */
    public static short port$get(MemorySegment seg) {
        return (short)constants$15.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint16_t port;
     * }
     */
    public static void port$set(MemorySegment seg, short x) {
        constants$15.const$2.set(seg, x);
    }
    public static short port$get(MemorySegment seg, long index) {
        return (short)constants$15.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void port$set(MemorySegment seg, long index, short x) {
        constants$15.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle cert_config$VH() {
        return constants$15.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_certificate_config_t* cert_config;
     * }
     */
    public static MemorySegment cert_config$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$15.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_certificate_config_t* cert_config;
     * }
     */
    public static void cert_config$set(MemorySegment seg, MemorySegment x) {
        constants$15.const$3.set(seg, x);
    }
    public static MemorySegment cert_config$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$15.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void cert_config$set(MemorySegment seg, long index, MemorySegment x) {
        constants$15.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_sessions_per_connection$VH() {
        return constants$15.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t max_sessions_per_connection;
     * }
     */
    public static int max_sessions_per_connection$get(MemorySegment seg) {
        return (int)constants$15.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t max_sessions_per_connection;
     * }
     */
    public static void max_sessions_per_connection$set(MemorySegment seg, int x) {
        constants$15.const$4.set(seg, x);
    }
    public static int max_sessions_per_connection$get(MemorySegment seg, long index) {
        return (int)constants$15.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void max_sessions_per_connection$set(MemorySegment seg, long index, int x) {
        constants$15.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_streams_per_session$VH() {
        return constants$15.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t max_streams_per_session;
     * }
     */
    public static int max_streams_per_session$get(MemorySegment seg) {
        return (int)constants$15.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t max_streams_per_session;
     * }
     */
    public static void max_streams_per_session$set(MemorySegment seg, int x) {
        constants$15.const$5.set(seg, x);
    }
    public static int max_streams_per_session$get(MemorySegment seg, long index) {
        return (int)constants$15.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void max_streams_per_session$set(MemorySegment seg, long index, int x) {
        constants$15.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle max_data_per_session$VH() {
        return constants$16.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint64_t max_data_per_session;
     * }
     */
    public static long max_data_per_session$get(MemorySegment seg) {
        return (long)constants$16.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint64_t max_data_per_session;
     * }
     */
    public static void max_data_per_session$set(MemorySegment seg, long x) {
        constants$16.const$0.set(seg, x);
    }
    public static long max_data_per_session$get(MemorySegment seg, long index) {
        return (long)constants$16.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void max_data_per_session$set(MemorySegment seg, long index, long x) {
        constants$16.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle idle_timeout_ms$VH() {
        return constants$16.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t idle_timeout_ms;
     * }
     */
    public static int idle_timeout_ms$get(MemorySegment seg) {
        return (int)constants$16.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t idle_timeout_ms;
     * }
     */
    public static void idle_timeout_ms$set(MemorySegment seg, int x) {
        constants$16.const$1.set(seg, x);
    }
    public static int idle_timeout_ms$get(MemorySegment seg, long index) {
        return (int)constants$16.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void idle_timeout_ms$set(MemorySegment seg, long index, int x) {
        constants$16.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle handshake_timeout_ms$VH() {
        return constants$16.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t handshake_timeout_ms;
     * }
     */
    public static int handshake_timeout_ms$get(MemorySegment seg) {
        return (int)constants$16.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t handshake_timeout_ms;
     * }
     */
    public static void handshake_timeout_ms$set(MemorySegment seg, int x) {
        constants$16.const$2.set(seg, x);
    }
    public static int handshake_timeout_ms$get(MemorySegment seg, long index) {
        return (int)constants$16.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void handshake_timeout_ms$set(MemorySegment seg, long index, int x) {
        constants$16.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enable_0rtt$VH() {
        return constants$16.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool enable_0rtt;
     * }
     */
    public static boolean enable_0rtt$get(MemorySegment seg) {
        return (boolean)constants$16.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool enable_0rtt;
     * }
     */
    public static void enable_0rtt$set(MemorySegment seg, boolean x) {
        constants$16.const$3.set(seg, x);
    }
    public static boolean enable_0rtt$get(MemorySegment seg, long index) {
        return (boolean)constants$16.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void enable_0rtt$set(MemorySegment seg, long index, boolean x) {
        constants$16.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enable_migration$VH() {
        return constants$16.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool enable_migration;
     * }
     */
    public static boolean enable_migration$get(MemorySegment seg) {
        return (boolean)constants$16.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool enable_migration;
     * }
     */
    public static void enable_migration$set(MemorySegment seg, boolean x) {
        constants$16.const$4.set(seg, x);
    }
    public static boolean enable_migration$get(MemorySegment seg, long index) {
        return (boolean)constants$16.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void enable_migration$set(MemorySegment seg, long index, boolean x) {
        constants$16.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle connection_validator$VH() {
        return constants$16.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_connection_validator_t connection_validator;
     * }
     */
    public static MemorySegment connection_validator$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$16.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_connection_validator_t connection_validator;
     * }
     */
    public static void connection_validator$set(MemorySegment seg, MemorySegment x) {
        constants$16.const$5.set(seg, x);
    }
    public static MemorySegment connection_validator$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$16.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void connection_validator$set(MemorySegment seg, long index, MemorySegment x) {
        constants$16.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static wtf_connection_validator_t connection_validator(MemorySegment segment, Arena scope) {
        return wtf_connection_validator_t.ofAddress(connection_validator$get(segment), scope);
    }
    public static VarHandle session_callback$VH() {
        return constants$17.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_session_callback_t session_callback;
     * }
     */
    public static MemorySegment session_callback$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_session_callback_t session_callback;
     * }
     */
    public static void session_callback$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$0.set(seg, x);
    }
    public static MemorySegment session_callback$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void session_callback$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static wtf_session_callback_t session_callback(MemorySegment segment, Arena scope) {
        return wtf_session_callback_t.ofAddress(session_callback$get(segment), scope);
    }
    public static VarHandle user_context$VH() {
        return constants$17.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static MemorySegment user_context$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$17.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static void user_context$set(MemorySegment seg, MemorySegment x) {
        constants$17.const$1.set(seg, x);
    }
    public static MemorySegment user_context$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$17.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void user_context$set(MemorySegment seg, long index, MemorySegment x) {
        constants$17.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


