// Generated by jextract

package com.structmap.webtransportfast.native;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*wtf_log_callback_t)(enum  level,char* component,char* file,int line,char* message,void* user_context);
 * }
 */
public interface wtf_log_callback_t {

    void apply(int level, java.lang.foreign.MemorySegment component, java.lang.foreign.MemorySegment file, int line, java.lang.foreign.MemorySegment message, java.lang.foreign.MemorySegment user_context);
    static MemorySegment allocate(wtf_log_callback_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$11.const$0, fi, constants$10.const$5, scope);
    }
    static wtf_log_callback_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _level, java.lang.foreign.MemorySegment _component, java.lang.foreign.MemorySegment _file, int _line, java.lang.foreign.MemorySegment _message, java.lang.foreign.MemorySegment _user_context) -> {
            try {
                constants$11.const$1.invokeExact(symbol, _level, _component, _file, _line, _message, _user_context);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


