// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final VarHandle const$0 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("state"));
    static final VarHandle const$1 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("length"));
    static final VarHandle const$2 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("data"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("stream"),
        RuntimeHelper.POINTER.withName("user_context"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buffers"),
                JAVA_INT.withName("buffer_count"),
                JAVA_BOOLEAN.withName("fin"),
                MemoryLayout.paddingLayout(3)
            ).withName("data_received"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("buffers"),
                JAVA_INT.withName("buffer_count"),
                JAVA_BOOLEAN.withName("cancelled"),
                MemoryLayout.paddingLayout(3)
            ).withName("send_complete"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("error_code")
            ).withName("aborted")
        ).withName("$anon$0")
    ).withName("");
    static final VarHandle const$4 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("stream"));
}


