// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(wtf_log_callback_t.class, "apply", constants$10.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$10.const$5
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("cert_type"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("cert_path"),
                RuntimeHelper.POINTER.withName("key_path")
            ).withName("file"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("cert_path"),
                RuntimeHelper.POINTER.withName("key_path"),
                RuntimeHelper.POINTER.withName("password")
            ).withName("protected_file"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("thumbprint")
            ).withName("hash"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("thumbprint"),
                RuntimeHelper.POINTER.withName("store_name")
            ).withName("hash_store"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("data"),
                JAVA_LONG.withName("data_size"),
                RuntimeHelper.POINTER.withName("password")
            ).withName("pkcs12"),
            RuntimeHelper.POINTER.withName("context")
        ).withName("cert_data"),
        RuntimeHelper.POINTER.withName("principal"),
        RuntimeHelper.POINTER.withName("ca_cert_file")
    ).withName("");
    static final VarHandle const$3 = constants$11.const$2.varHandle(MemoryLayout.PathElement.groupElement("cert_type"));
    static final UnionLayout const$4 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("cert_path"),
            RuntimeHelper.POINTER.withName("key_path")
        ).withName("file"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("cert_path"),
            RuntimeHelper.POINTER.withName("key_path"),
            RuntimeHelper.POINTER.withName("password")
        ).withName("protected_file"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("thumbprint")
        ).withName("hash"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("thumbprint"),
            RuntimeHelper.POINTER.withName("store_name")
        ).withName("hash_store"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_LONG.withName("data_size"),
            RuntimeHelper.POINTER.withName("password")
        ).withName("pkcs12"),
        RuntimeHelper.POINTER.withName("context")
    ).withName("");
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("cert_path"),
        RuntimeHelper.POINTER.withName("key_path")
    ).withName("");
}


