// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("stream"),
        JAVA_INT.withName("stream_type"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$1 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("stream"));
    static final VarHandle const$2 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("stream_type"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("buffers"),
        JAVA_INT.withName("buffer_count"),
        JAVA_INT.withName("state")
    ).withName("");
    static final VarHandle const$4 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("buffers"));
    static final VarHandle const$5 = constants$5.const$3.varHandle(MemoryLayout.PathElement.groupElement("buffer_count"));
}


