// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final VarHandle const$0 = constants$3.const$5.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$1 = constants$3.const$5.varHandle(MemoryLayout.PathElement.groupElement("session"));
    static final VarHandle const$2 = constants$3.const$5.varHandle(MemoryLayout.PathElement.groupElement("user_context"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("error_code"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("reason")
    ).withName("");
    static final VarHandle const$4 = constants$4.const$3.varHandle(MemoryLayout.PathElement.groupElement("error_code"));
    static final VarHandle const$5 = constants$4.const$3.varHandle(MemoryLayout.PathElement.groupElement("reason"));
}


