// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wtf_server_stop",
        constants$20.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wtf_server_get_state",
        constants$20.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wtf_server_destroy",
        constants$0.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wtf_session_close",
        constants$21.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wtf_session_drain",
        constants$20.const$5
    );
}


