// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final VarHandle const$0 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("session_callback"));
    static final VarHandle const$1 = constants$15.const$0.varHandle(MemoryLayout.PathElement.groupElement("user_context"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("log_level"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("log_callback"),
        RuntimeHelper.POINTER.withName("log_user_context"),
        JAVA_INT.withName("worker_thread_count"),
        JAVA_BOOLEAN.withName("enable_load_balancing"),
        JAVA_BOOLEAN.withName("disable_encryption"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("execution_profile"),
        MemoryLayout.paddingLayout(4)
    ).withName("");
    static final VarHandle const$3 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("log_level"));
    static final VarHandle const$4 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("log_callback"));
    static final VarHandle const$5 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("log_user_context"));
}


