// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(wtf_connection_validator_t.class, "apply", constants$9.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$9.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(wtf_session_callback_t.class, "apply", constants$0.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(wtf_stream_callback_t.class, "apply", constants$0.const$0);
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


