// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "wtf_stream_get_id",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wtf_stream_set_callback",
        constants$22.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wtf_stream_set_context",
        constants$22.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "wtf_stream_get_context",
        constants$23.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wtf_stream_get_type",
        constants$20.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "wtf_stream_get_state",
        constants$20.const$5
    );
}


