// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final VarHandle const$0 = constants$7.const$5.varHandle(MemoryLayout.PathElement.groupElement("buffers"));
    static final VarHandle const$1 = constants$7.const$5.varHandle(MemoryLayout.PathElement.groupElement("buffer_count"));
    static final VarHandle const$2 = constants$7.const$5.varHandle(MemoryLayout.PathElement.groupElement("cancelled"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("error_code")
    ).withName("");
    static final VarHandle const$4 = constants$8.const$3.varHandle(MemoryLayout.PathElement.groupElement("error_code"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("error_code"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("description"),
        JAVA_BOOLEAN.withName("is_application_error"),
        JAVA_BOOLEAN.withName("is_transport_error"),
        JAVA_BOOLEAN.withName("is_protocol_error"),
        MemoryLayout.paddingLayout(5)
    ).withName("");
}


