// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("cert_path"));
    static final VarHandle const$1 = constants$11.const$5.varHandle(MemoryLayout.PathElement.groupElement("key_path"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("cert_path"),
        RuntimeHelper.POINTER.withName("key_path"),
        RuntimeHelper.POINTER.withName("password")
    ).withName("");
    static final VarHandle const$3 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("cert_path"));
    static final VarHandle const$4 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("key_path"));
    static final VarHandle const$5 = constants$12.const$2.varHandle(MemoryLayout.PathElement.groupElement("password"));
}


