// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final VarHandle const$0 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("worker_thread_count"));
    static final VarHandle const$1 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("enable_load_balancing"));
    static final VarHandle const$2 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("disable_encryption"));
    static final VarHandle const$3 = constants$17.const$2.varHandle(MemoryLayout.PathElement.groupElement("execution_profile"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("major"),
        JAVA_INT.withName("minor"),
        JAVA_INT.withName("patch"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("version")
    ).withName("");
    static final VarHandle const$5 = constants$18.const$4.varHandle(MemoryLayout.PathElement.groupElement("major"));
}


