// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "wtf_session_send_datagram",
        constants$22.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "wtf_session_create_stream",
        constants$21.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "wtf_session_get_state",
        constants$20.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "wtf_session_get_peer_address",
        constants$20.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "wtf_session_set_context",
        constants$22.const$5
    );
}


