// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*wtf_stream_callback_t)(struct * event);
 * }
 */
public interface wtf_stream_callback_t {

    void apply(java.lang.foreign.MemorySegment event);
    static MemorySegment allocate(wtf_stream_callback_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$10.const$4, fi, constants$0.const$0, scope);
    }
    static wtf_stream_callback_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _event) -> {
            try {
                constants$10.const$3.invokeExact(symbol, _event);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


