// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     wtf_stream_event_type_t type;
 *     wtf_stream_t* stream;
 *     void* user_context;
 *     union {
 *         struct  data_received;
 *         struct  send_complete;
 *         struct  aborted;
 *     };
 * };
 * }
 */
public class wtf_stream_event_t {

    public static MemoryLayout $LAYOUT() {
        return constants$6.const$3;
    }
    public static VarHandle type$VH() {
        return constants$6.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_stream_event_type_t type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$6.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_stream_event_type_t type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$6.const$4.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$6.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$6.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle stream$VH() {
        return constants$6.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_stream_t* stream;
     * }
     */
    public static MemorySegment stream$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_stream_t* stream;
     * }
     */
    public static void stream$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$5.set(seg, x);
    }
    public static MemorySegment stream$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void stream$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle user_context$VH() {
        return constants$7.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static MemorySegment user_context$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$7.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static void user_context$set(MemorySegment seg, MemorySegment x) {
        constants$7.const$0.set(seg, x);
    }
    public static MemorySegment user_context$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$7.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void user_context$set(MemorySegment seg, long index, MemorySegment x) {
        constants$7.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * struct {
     *     wtf_buffer_t* buffers;
     *     uint32_t buffer_count;
     *     _Bool fin;
     * };
     * }
     */
    public static final class data_received {

        // Suppresses default constructor, ensuring non-instantiability.
        private data_received() {}
        public static MemoryLayout $LAYOUT() {
            return constants$7.const$1;
        }
        public static VarHandle buffers$VH() {
            return constants$7.const$2;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static MemorySegment buffers$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$7.const$2.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static void buffers$set(MemorySegment seg, MemorySegment x) {
            constants$7.const$2.set(seg, x);
        }
        public static MemorySegment buffers$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$7.const$2.get(seg.asSlice(index*sizeof()));
        }
        public static void buffers$set(MemorySegment seg, long index, MemorySegment x) {
            constants$7.const$2.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle buffer_count$VH() {
            return constants$7.const$3;
        }
        /**
         * Getter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static int buffer_count$get(MemorySegment seg) {
            return (int)constants$7.const$3.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static void buffer_count$set(MemorySegment seg, int x) {
            constants$7.const$3.set(seg, x);
        }
        public static int buffer_count$get(MemorySegment seg, long index) {
            return (int)constants$7.const$3.get(seg.asSlice(index*sizeof()));
        }
        public static void buffer_count$set(MemorySegment seg, long index, int x) {
            constants$7.const$3.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle fin$VH() {
            return constants$7.const$4;
        }
        /**
         * Getter for field:
         * {@snippet :
         * _Bool fin;
         * }
         */
        public static boolean fin$get(MemorySegment seg) {
            return (boolean)constants$7.const$4.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * _Bool fin;
         * }
         */
        public static void fin$set(MemorySegment seg, boolean x) {
            constants$7.const$4.set(seg, x);
        }
        public static boolean fin$get(MemorySegment seg, long index) {
            return (boolean)constants$7.const$4.get(seg.asSlice(index*sizeof()));
        }
        public static void fin$set(MemorySegment seg, long index, boolean x) {
            constants$7.const$4.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment data_received$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    /**
     * {@snippet :
     * struct {
     *     wtf_buffer_t* buffers;
     *     uint32_t buffer_count;
     *     _Bool cancelled;
     * };
     * }
     */
    public static final class send_complete {

        // Suppresses default constructor, ensuring non-instantiability.
        private send_complete() {}
        public static MemoryLayout $LAYOUT() {
            return constants$7.const$5;
        }
        public static VarHandle buffers$VH() {
            return constants$8.const$0;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static MemorySegment buffers$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$8.const$0.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static void buffers$set(MemorySegment seg, MemorySegment x) {
            constants$8.const$0.set(seg, x);
        }
        public static MemorySegment buffers$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$8.const$0.get(seg.asSlice(index*sizeof()));
        }
        public static void buffers$set(MemorySegment seg, long index, MemorySegment x) {
            constants$8.const$0.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle buffer_count$VH() {
            return constants$8.const$1;
        }
        /**
         * Getter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static int buffer_count$get(MemorySegment seg) {
            return (int)constants$8.const$1.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static void buffer_count$set(MemorySegment seg, int x) {
            constants$8.const$1.set(seg, x);
        }
        public static int buffer_count$get(MemorySegment seg, long index) {
            return (int)constants$8.const$1.get(seg.asSlice(index*sizeof()));
        }
        public static void buffer_count$set(MemorySegment seg, long index, int x) {
            constants$8.const$1.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle cancelled$VH() {
            return constants$8.const$2;
        }
        /**
         * Getter for field:
         * {@snippet :
         * _Bool cancelled;
         * }
         */
        public static boolean cancelled$get(MemorySegment seg) {
            return (boolean)constants$8.const$2.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * _Bool cancelled;
         * }
         */
        public static void cancelled$set(MemorySegment seg, boolean x) {
            constants$8.const$2.set(seg, x);
        }
        public static boolean cancelled$get(MemorySegment seg, long index) {
            return (boolean)constants$8.const$2.get(seg.asSlice(index*sizeof()));
        }
        public static void cancelled$set(MemorySegment seg, long index, boolean x) {
            constants$8.const$2.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment send_complete$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    /**
     * {@snippet :
     * struct {
     *     uint32_t error_code;
     * };
     * }
     */
    public static final class aborted {

        // Suppresses default constructor, ensuring non-instantiability.
        private aborted() {}
        public static MemoryLayout $LAYOUT() {
            return constants$8.const$3;
        }
        public static VarHandle error_code$VH() {
            return constants$8.const$4;
        }
        /**
         * Getter for field:
         * {@snippet :
         * uint32_t error_code;
         * }
         */
        public static int error_code$get(MemorySegment seg) {
            return (int)constants$8.const$4.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * uint32_t error_code;
         * }
         */
        public static void error_code$set(MemorySegment seg, int x) {
            constants$8.const$4.set(seg, x);
        }
        public static int error_code$get(MemorySegment seg, long index) {
            return (int)constants$8.const$4.get(seg.asSlice(index*sizeof()));
        }
        public static void error_code$set(MemorySegment seg, long index, int x) {
            constants$8.const$4.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment aborted$slice(MemorySegment seg) {
        return seg.asSlice(24, 4);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


