// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct wtf_server wtf_server_t;
 * }
 */
public final class wtf_server_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private wtf_server_t() {}
}


