// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * enum  (*wtf_connection_validator_t)(struct * request,void* user_context);
 * }
 */
public interface wtf_connection_validator_t {

    int apply(java.lang.foreign.MemorySegment request, java.lang.foreign.MemorySegment user_context);
    static MemorySegment allocate(wtf_connection_validator_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$10.const$0, fi, constants$9.const$5, scope);
    }
    static wtf_connection_validator_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _request, java.lang.foreign.MemorySegment _user_context) -> {
            try {
                return (int)constants$10.const$1.invokeExact(symbol, _request, _user_context);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


