// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class wtf_h  {

    public static final OfByte C_CHAR = JAVA_BYTE;
    public static final OfShort C_SHORT = JAVA_SHORT;
    public static final OfInt C_INT = JAVA_INT;
    public static final OfInt C_LONG = JAVA_INT;
    public static final OfLong C_LONG_LONG = JAVA_LONG;
    public static final OfFloat C_FLOAT = JAVA_FLOAT;
    public static final OfDouble C_DOUBLE = JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = RuntimeHelper.POINTER;
    /**
     * {@snippet :
     * #define true 1
     * }
     */
    public static int true_() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define false 0
     * }
     */
    public static int false_() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define __bool_true_false_are_defined 1
     * }
     */
    public static int __bool_true_false_are_defined() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _VCRT_COMPILER_PREPROCESSOR 1
     * }
     */
    public static int _VCRT_COMPILER_PREPROCESSOR() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _SAL_VERSION 20
     * }
     */
    public static int _SAL_VERSION() {
        return (int)20L;
    }
    /**
     * {@snippet :
     * #define __SAL_H_VERSION 180000000
     * }
     */
    public static int __SAL_H_VERSION() {
        return (int)180000000L;
    }
    /**
     * {@snippet :
     * #define _USE_DECLSPECS_FOR_SAL 0
     * }
     */
    public static int _USE_DECLSPECS_FOR_SAL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _USE_ATTRIBUTES_FOR_SAL 0
     * }
     */
    public static int _USE_ATTRIBUTES_FOR_SAL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _CRT_PACKING 8
     * }
     */
    public static int _CRT_PACKING() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * #define _HAS_EXCEPTIONS 1
     * }
     */
    public static int _HAS_EXCEPTIONS() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * #define _HAS_CXX17 0
     * }
     */
    public static int _HAS_CXX17() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _HAS_CXX20 0
     * }
     */
    public static int _HAS_CXX20() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _HAS_CXX23 0
     * }
     */
    public static int _HAS_CXX23() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _HAS_CXX26 0
     * }
     */
    public static int _HAS_CXX26() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define _HAS_NODISCARD 0
     * }
     */
    public static int _HAS_NODISCARD() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define WCHAR_MIN 0
     * }
     */
    public static int WCHAR_MIN() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define WCHAR_MAX 65535
     * }
     */
    public static int WCHAR_MAX() {
        return (int)65535L;
    }
    /**
     * {@snippet :
     * #define WINT_MIN 0
     * }
     */
    public static int WINT_MIN() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define WINT_MAX 65535
     * }
     */
    public static int WINT_MAX() {
        return (int)65535L;
    }
    /**
     * {@snippet :
     * #define WTF_WEBTRANSPORT_BUFFERED_STREAM_REJECTED 966049156
     * }
     */
    public static int WTF_WEBTRANSPORT_BUFFERED_STREAM_REJECTED() {
        return (int)966049156L;
    }
    /**
     * {@snippet :
     * #define WTF_WEBTRANSPORT_SESSION_GONE 386759528
     * }
     */
    public static int WTF_WEBTRANSPORT_SESSION_GONE() {
        return (int)386759528L;
    }
    /**
     * {@snippet :
     * typedef long long ptrdiff_t;
     * }
     */
    public static final OfLong ptrdiff_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long long size_t;
     * }
     */
    public static final OfLong size_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned short wchar_t;
     * }
     */
    public static final OfShort wchar_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef double max_align_t;
     * }
     */
    public static final OfDouble max_align_t = JAVA_DOUBLE;
    /**
     * {@snippet :
     * typedef unsigned long long uintptr_t;
     * }
     */
    public static final OfLong uintptr_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef char* va_list;
     * }
     */
    public static final AddressLayout va_list = RuntimeHelper.POINTER;
    public static MethodHandle __va_start$MH() {
        return RuntimeHelper.requireNonNull(constants$0.const$1,"__va_start");
    }
    /**
     * {@snippet :
     * void __va_start(va_list*,...);
     * }
     */
    public static void __va_start(MemorySegment x0, Object... x1) {
        var mh$ = __va_start$MH();
        try {
            mh$.invokeExact(x0, x1);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * typedef long long intptr_t;
     * }
     */
    public static final OfLong intptr_t = JAVA_LONG;
    public static MethodHandle __security_init_cookie$MH() {
        return RuntimeHelper.requireNonNull(constants$0.const$3,"__security_init_cookie");
    }
    /**
     * {@snippet :
     * void __security_init_cookie();
     * }
     */
    public static void __security_init_cookie() {
        var mh$ = __security_init_cookie$MH();
        try {
            mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle __security_check_cookie$MH() {
        return RuntimeHelper.requireNonNull(constants$0.const$5,"__security_check_cookie");
    }
    /**
     * {@snippet :
     * void __security_check_cookie(uintptr_t _StackCookie);
     * }
     */
    public static void __security_check_cookie(long _StackCookie) {
        var mh$ = __security_check_cookie$MH();
        try {
            mh$.invokeExact(_StackCookie);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle __report_gsfailure$MH() {
        return RuntimeHelper.requireNonNull(constants$1.const$0,"__report_gsfailure");
    }
    /**
     * {@snippet :
     * void __report_gsfailure(uintptr_t _StackCookie);
     * }
     */
    public static void __report_gsfailure(long _StackCookie) {
        var mh$ = __report_gsfailure$MH();
        try {
            mh$.invokeExact(_StackCookie);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MemoryLayout __security_cookie$LAYOUT() {
        return JAVA_LONG;
    }
    public static VarHandle __security_cookie$VH() {
        return constants$1.const$1;
    }
    public static MemorySegment __security_cookie$SEGMENT() {
        return RuntimeHelper.requireNonNull(constants$1.const$2,"__security_cookie");
    }
    /**
     * Getter for variable:
     * {@snippet :
     * uintptr_t __security_cookie;
     * }
     */
    public static long __security_cookie$get() {
        return (long) constants$1.const$1.get(RuntimeHelper.requireNonNull(constants$1.const$2, "__security_cookie"));
    }
    /**
     * Setter for variable:
     * {@snippet :
     * uintptr_t __security_cookie;
     * }
     */
    public static void __security_cookie$set(long x) {
        constants$1.const$1.set(RuntimeHelper.requireNonNull(constants$1.const$2, "__security_cookie"), x);
    }
    /**
     * {@snippet :
     * typedef signed char int8_t;
     * }
     */
    public static final OfByte int8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short int16_t;
     * }
     */
    public static final OfShort int16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int int32_t;
     * }
     */
    public static final OfInt int32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long long int64_t;
     * }
     */
    public static final OfLong int64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint8_t;
     * }
     */
    public static final OfByte uint8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned short uint16_t;
     * }
     */
    public static final OfShort uint16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned int uint32_t;
     * }
     */
    public static final OfInt uint32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long long uint64_t;
     * }
     */
    public static final OfLong uint64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char int_least8_t;
     * }
     */
    public static final OfByte int_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef short int_least16_t;
     * }
     */
    public static final OfShort int_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef int int_least32_t;
     * }
     */
    public static final OfInt int_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long long int_least64_t;
     * }
     */
    public static final OfLong int_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint_least8_t;
     * }
     */
    public static final OfByte uint_least8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned short uint_least16_t;
     * }
     */
    public static final OfShort uint_least16_t = JAVA_SHORT;
    /**
     * {@snippet :
     * typedef unsigned int uint_least32_t;
     * }
     */
    public static final OfInt uint_least32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long long uint_least64_t;
     * }
     */
    public static final OfLong uint_least64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef signed char int_fast8_t;
     * }
     */
    public static final OfByte int_fast8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef int int_fast16_t;
     * }
     */
    public static final OfInt int_fast16_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef int int_fast32_t;
     * }
     */
    public static final OfInt int_fast32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef long long int_fast64_t;
     * }
     */
    public static final OfLong int_fast64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned char uint_fast8_t;
     * }
     */
    public static final OfByte uint_fast8_t = JAVA_BYTE;
    /**
     * {@snippet :
     * typedef unsigned int uint_fast16_t;
     * }
     */
    public static final OfInt uint_fast16_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned int uint_fast32_t;
     * }
     */
    public static final OfInt uint_fast32_t = JAVA_INT;
    /**
     * {@snippet :
     * typedef unsigned long long uint_fast64_t;
     * }
     */
    public static final OfLong uint_fast64_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef long long intmax_t;
     * }
     */
    public static final OfLong intmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * typedef unsigned long long uintmax_t;
     * }
     */
    public static final OfLong uintmax_t = JAVA_LONG;
    /**
     * {@snippet :
     * enum .WTF_EXECUTION_PROFILE_LOW_LATENCY = 0;
     * }
     */
    public static int WTF_EXECUTION_PROFILE_LOW_LATENCY() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_EXECUTION_PROFILE_MAX_THROUGHPUT = 1;
     * }
     */
    public static int WTF_EXECUTION_PROFILE_MAX_THROUGHPUT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_EXECUTION_PROFILE_REAL_TIME = 2;
     * }
     */
    public static int WTF_EXECUTION_PROFILE_REAL_TIME() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_EXECUTION_PROFILE_SCAVENGER = 3;
     * }
     */
    public static int WTF_EXECUTION_PROFILE_SCAVENGER() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_SUCCESS = 0;
     * }
     */
    public static int WTF_SUCCESS() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_INVALID_PARAMETER = 1;
     * }
     */
    public static int WTF_ERROR_INVALID_PARAMETER() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_OUT_OF_MEMORY = 2;
     * }
     */
    public static int WTF_ERROR_OUT_OF_MEMORY() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_INTERNAL = 3;
     * }
     */
    public static int WTF_ERROR_INTERNAL() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_CONNECTION_ABORTED = 4;
     * }
     */
    public static int WTF_ERROR_CONNECTION_ABORTED() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_STREAM_ABORTED = 5;
     * }
     */
    public static int WTF_ERROR_STREAM_ABORTED() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_INVALID_STATE = 6;
     * }
     */
    public static int WTF_ERROR_INVALID_STATE() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_BUFFER_TOO_SMALL = 7;
     * }
     */
    public static int WTF_ERROR_BUFFER_TOO_SMALL() {
        return (int)7L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_NOT_FOUND = 8;
     * }
     */
    public static int WTF_ERROR_NOT_FOUND() {
        return (int)8L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_REJECTED = 9;
     * }
     */
    public static int WTF_ERROR_REJECTED() {
        return (int)9L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_TIMEOUT = 10;
     * }
     */
    public static int WTF_ERROR_TIMEOUT() {
        return (int)10L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_TLS_HANDSHAKE_FAILED = 11;
     * }
     */
    public static int WTF_ERROR_TLS_HANDSHAKE_FAILED() {
        return (int)11L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_PROTOCOL_VIOLATION = 12;
     * }
     */
    public static int WTF_ERROR_PROTOCOL_VIOLATION() {
        return (int)12L;
    }
    /**
     * {@snippet :
     * enum .WTF_ERROR_FLOW_CONTROL = 13;
     * }
     */
    public static int WTF_ERROR_FLOW_CONTROL() {
        return (int)13L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_TRACE = 0;
     * }
     */
    public static int WTF_LOG_LEVEL_TRACE() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_DEBUG = 1;
     * }
     */
    public static int WTF_LOG_LEVEL_DEBUG() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_INFO = 2;
     * }
     */
    public static int WTF_LOG_LEVEL_INFO() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_WARN = 3;
     * }
     */
    public static int WTF_LOG_LEVEL_WARN() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_ERROR = 4;
     * }
     */
    public static int WTF_LOG_LEVEL_ERROR() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_CRITICAL = 5;
     * }
     */
    public static int WTF_LOG_LEVEL_CRITICAL() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum .WTF_LOG_LEVEL_NONE = 6;
     * }
     */
    public static int WTF_LOG_LEVEL_NONE() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * enum .WTF_SERVER_STOPPED = 0;
     * }
     */
    public static int WTF_SERVER_STOPPED() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_SERVER_STARTING = 1;
     * }
     */
    public static int WTF_SERVER_STARTING() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_SERVER_LISTENING = 2;
     * }
     */
    public static int WTF_SERVER_LISTENING() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_SERVER_STOPPING = 3;
     * }
     */
    public static int WTF_SERVER_STOPPING() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_HANDSHAKING = 0;
     * }
     */
    public static int WTF_SESSION_HANDSHAKING() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_CONNECTED = 1;
     * }
     */
    public static int WTF_SESSION_CONNECTED() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_DRAINING = 2;
     * }
     */
    public static int WTF_SESSION_DRAINING() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_CLOSED = 3;
     * }
     */
    public static int WTF_SESSION_CLOSED() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_OPEN = 0;
     * }
     */
    public static int WTF_STREAM_OPEN() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_CLOSING = 1;
     * }
     */
    public static int WTF_STREAM_CLOSING() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_CLOSED = 2;
     * }
     */
    public static int WTF_STREAM_CLOSED() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_BIDIRECTIONAL = 0;
     * }
     */
    public static int WTF_STREAM_BIDIRECTIONAL() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_UNIDIRECTIONAL = 1;
     * }
     */
    public static int WTF_STREAM_UNIDIRECTIONAL() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_CONNECTION_ACCEPT = 0;
     * }
     */
    public static int WTF_CONNECTION_ACCEPT() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_CONNECTION_REJECT = 1;
     * }
     */
    public static int WTF_CONNECTION_REJECT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_NO_ERROR = 256;
     * }
     */
    public static int WTF_H3_NO_ERROR() {
        return (int)256L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_GENERAL_PROTOCOL_ERROR = 257;
     * }
     */
    public static int WTF_H3_GENERAL_PROTOCOL_ERROR() {
        return (int)257L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_INTERNAL_ERROR = 258;
     * }
     */
    public static int WTF_H3_INTERNAL_ERROR() {
        return (int)258L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_STREAM_CREATION_ERROR = 259;
     * }
     */
    public static int WTF_H3_STREAM_CREATION_ERROR() {
        return (int)259L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_CLOSED_CRITICAL_STREAM = 260;
     * }
     */
    public static int WTF_H3_CLOSED_CRITICAL_STREAM() {
        return (int)260L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_FRAME_UNEXPECTED = 261;
     * }
     */
    public static int WTF_H3_FRAME_UNEXPECTED() {
        return (int)261L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_FRAME_ERROR = 262;
     * }
     */
    public static int WTF_H3_FRAME_ERROR() {
        return (int)262L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_EXCESSIVE_LOAD = 263;
     * }
     */
    public static int WTF_H3_EXCESSIVE_LOAD() {
        return (int)263L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_ID_ERROR = 264;
     * }
     */
    public static int WTF_H3_ID_ERROR() {
        return (int)264L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_SETTINGS_ERROR = 265;
     * }
     */
    public static int WTF_H3_SETTINGS_ERROR() {
        return (int)265L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_MISSING_SETTINGS = 266;
     * }
     */
    public static int WTF_H3_MISSING_SETTINGS() {
        return (int)266L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_REQUEST_REJECTED = 267;
     * }
     */
    public static int WTF_H3_REQUEST_REJECTED() {
        return (int)267L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_REQUEST_CANCELLED = 268;
     * }
     */
    public static int WTF_H3_REQUEST_CANCELLED() {
        return (int)268L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_REQUEST_INCOMPLETE = 269;
     * }
     */
    public static int WTF_H3_REQUEST_INCOMPLETE() {
        return (int)269L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_MESSAGE_ERROR = 270;
     * }
     */
    public static int WTF_H3_MESSAGE_ERROR() {
        return (int)270L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_CONNECT_ERROR = 271;
     * }
     */
    public static int WTF_H3_CONNECT_ERROR() {
        return (int)271L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_VERSION_FALLBACK = 272;
     * }
     */
    public static int WTF_H3_VERSION_FALLBACK() {
        return (int)272L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_UNKNOWN = 0;
     * }
     */
    public static int WTF_DATAGRAM_SEND_UNKNOWN() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_SENT = 1;
     * }
     */
    public static int WTF_DATAGRAM_SEND_SENT() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_LOST_SUSPECTED = 2;
     * }
     */
    public static int WTF_DATAGRAM_SEND_LOST_SUSPECTED() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_LOST_DISCARDED = 3;
     * }
     */
    public static int WTF_DATAGRAM_SEND_LOST_DISCARDED() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_ACKNOWLEDGED = 4;
     * }
     */
    public static int WTF_DATAGRAM_SEND_ACKNOWLEDGED() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_ACKNOWLEDGED_SPURIOUS = 5;
     * }
     */
    public static int WTF_DATAGRAM_SEND_ACKNOWLEDGED_SPURIOUS() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum .WTF_DATAGRAM_SEND_CANCELED = 6;
     * }
     */
    public static int WTF_DATAGRAM_SEND_CANCELED() {
        return (int)6L;
    }
    /**
     * {@snippet :
     * enum .WTF_QPACK_DECOMPRESSION_FAILED = 512;
     * }
     */
    public static int WTF_QPACK_DECOMPRESSION_FAILED() {
        return (int)512L;
    }
    /**
     * {@snippet :
     * enum .WTF_QPACK_ENCODER_STREAM_ERROR = 513;
     * }
     */
    public static int WTF_QPACK_ENCODER_STREAM_ERROR() {
        return (int)513L;
    }
    /**
     * {@snippet :
     * enum .WTF_QPACK_DECODER_STREAM_ERROR = 514;
     * }
     */
    public static int WTF_QPACK_DECODER_STREAM_ERROR() {
        return (int)514L;
    }
    /**
     * {@snippet :
     * enum .WTF_H3_DATAGRAM_ERROR = 51;
     * }
     */
    public static int WTF_H3_DATAGRAM_ERROR() {
        return (int)51L;
    }
    /**
     * {@snippet :
     * enum .WTF_CAPSULE_DATAGRAM = 0;
     * }
     */
    public static int WTF_CAPSULE_DATAGRAM() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_CAPSULE_CLOSE_WEBTRANSPORT_SESSION = 10307;
     * }
     */
    public static int WTF_CAPSULE_CLOSE_WEBTRANSPORT_SESSION() {
        return (int)10307L;
    }
    /**
     * {@snippet :
     * enum .WTF_CAPSULE_DRAIN_WEBTRANSPORT_SESSION = 30894;
     * }
     */
    public static int WTF_CAPSULE_DRAIN_WEBTRANSPORT_SESSION() {
        return (int)30894L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_CONNECTED = 0;
     * }
     */
    public static int WTF_SESSION_EVENT_CONNECTED() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_DISCONNECTED = 1;
     * }
     */
    public static int WTF_SESSION_EVENT_DISCONNECTED() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_DRAINING = 2;
     * }
     */
    public static int WTF_SESSION_EVENT_DRAINING() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_STREAM_OPENED = 3;
     * }
     */
    public static int WTF_SESSION_EVENT_STREAM_OPENED() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_DATAGRAM_SEND_STATE_CHANGE = 4;
     * }
     */
    public static int WTF_SESSION_EVENT_DATAGRAM_SEND_STATE_CHANGE() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_SESSION_EVENT_DATAGRAM_RECEIVED = 5;
     * }
     */
    public static int WTF_SESSION_EVENT_DATAGRAM_RECEIVED() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_EVENT_DATA_RECEIVED = 0;
     * }
     */
    public static int WTF_STREAM_EVENT_DATA_RECEIVED() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_EVENT_SEND_COMPLETE = 1;
     * }
     */
    public static int WTF_STREAM_EVENT_SEND_COMPLETE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_EVENT_PEER_CLOSED = 2;
     * }
     */
    public static int WTF_STREAM_EVENT_PEER_CLOSED() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_EVENT_CLOSED = 3;
     * }
     */
    public static int WTF_STREAM_EVENT_CLOSED() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_STREAM_EVENT_ABORTED = 4;
     * }
     */
    public static int WTF_STREAM_EVENT_ABORTED() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_NONE = 0;
     * }
     */
    public static int WTF_CERT_TYPE_NONE() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_FILE = 1;
     * }
     */
    public static int WTF_CERT_TYPE_FILE() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_FILE_PROTECTED = 2;
     * }
     */
    public static int WTF_CERT_TYPE_FILE_PROTECTED() {
        return (int)2L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_HASH = 3;
     * }
     */
    public static int WTF_CERT_TYPE_HASH() {
        return (int)3L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_HASH_STORE = 4;
     * }
     */
    public static int WTF_CERT_TYPE_HASH_STORE() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_CONTEXT = 5;
     * }
     */
    public static int WTF_CERT_TYPE_CONTEXT() {
        return (int)5L;
    }
    /**
     * {@snippet :
     * enum .WTF_CERT_TYPE_PKCS12 = 6;
     * }
     */
    public static int WTF_CERT_TYPE_PKCS12() {
        return (int)6L;
    }
    public static MethodHandle wtf_get_version$MH() {
        return RuntimeHelper.requireNonNull(constants$19.const$4,"wtf_get_version");
    }
    /**
     * {@snippet :
     * wtf_version_info_t* wtf_get_version(,...);
     * }
     */
    public static MemorySegment wtf_get_version(Object... x0) {
        var mh$ = wtf_get_version$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(x0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_context_create$MH() {
        return RuntimeHelper.requireNonNull(constants$19.const$5,"wtf_context_create");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_context_create(const wtf_context_config_t* config, wtf_context_t** context);
     * }
     */
    public static int wtf_context_create(MemorySegment config, MemorySegment context) {
        var mh$ = wtf_context_create$MH();
        try {
            return (int)mh$.invokeExact(config, context);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_context_destroy$MH() {
        return RuntimeHelper.requireNonNull(constants$20.const$0,"wtf_context_destroy");
    }
    /**
     * {@snippet :
     * void wtf_context_destroy(wtf_context_t* context);
     * }
     */
    public static void wtf_context_destroy(MemorySegment context) {
        var mh$ = wtf_context_destroy$MH();
        try {
            mh$.invokeExact(context);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_context_set_log_level$MH() {
        return RuntimeHelper.requireNonNull(constants$20.const$2,"wtf_context_set_log_level");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_context_set_log_level(wtf_context_t* context, wtf_log_level_t level);
     * }
     */
    public static int wtf_context_set_log_level(MemorySegment context, int level) {
        var mh$ = wtf_context_set_log_level$MH();
        try {
            return (int)mh$.invokeExact(context, level);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_server_create$MH() {
        return RuntimeHelper.requireNonNull(constants$20.const$4,"wtf_server_create");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_server_create(wtf_context_t* context, const wtf_server_config_t* config, wtf_server_t** server);
     * }
     */
    public static int wtf_server_create(MemorySegment context, MemorySegment config, MemorySegment server) {
        var mh$ = wtf_server_create$MH();
        try {
            return (int)mh$.invokeExact(context, config, server);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_server_start$MH() {
        return RuntimeHelper.requireNonNull(constants$20.const$6,"wtf_server_start");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_server_start(wtf_server_t* server);
     * }
     */
    public static int wtf_server_start(MemorySegment server) {
        var mh$ = wtf_server_start$MH();
        try {
            return (int)mh$.invokeExact(server);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_server_stop$MH() {
        return RuntimeHelper.requireNonNull(constants$21.const$0,"wtf_server_stop");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_server_stop(wtf_server_t* server);
     * }
     */
    public static int wtf_server_stop(MemorySegment server) {
        var mh$ = wtf_server_stop$MH();
        try {
            return (int)mh$.invokeExact(server);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_server_get_state$MH() {
        return RuntimeHelper.requireNonNull(constants$21.const$1,"wtf_server_get_state");
    }
    /**
     * {@snippet :
     * wtf_server_state_t wtf_server_get_state(wtf_server_t* server);
     * }
     */
    public static int wtf_server_get_state(MemorySegment server) {
        var mh$ = wtf_server_get_state$MH();
        try {
            return (int)mh$.invokeExact(server);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_server_destroy$MH() {
        return RuntimeHelper.requireNonNull(constants$21.const$2,"wtf_server_destroy");
    }
    /**
     * {@snippet :
     * void wtf_server_destroy(wtf_server_t* server);
     * }
     */
    public static void wtf_server_destroy(MemorySegment server) {
        var mh$ = wtf_server_destroy$MH();
        try {
            mh$.invokeExact(server);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_close$MH() {
        return RuntimeHelper.requireNonNull(constants$21.const$4,"wtf_session_close");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_session_close(wtf_session_t* session, uint32_t error_code, char* reason);
     * }
     */
    public static int wtf_session_close(MemorySegment session, int error_code, MemorySegment reason) {
        var mh$ = wtf_session_close$MH();
        try {
            return (int)mh$.invokeExact(session, error_code, reason);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_drain$MH() {
        return RuntimeHelper.requireNonNull(constants$21.const$5,"wtf_session_drain");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_session_drain(wtf_session_t* session);
     * }
     */
    public static int wtf_session_drain(MemorySegment session) {
        var mh$ = wtf_session_drain$MH();
        try {
            return (int)mh$.invokeExact(session);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_send_datagram$MH() {
        return RuntimeHelper.requireNonNull(constants$22.const$1,"wtf_session_send_datagram");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_session_send_datagram(wtf_session_t* session, const wtf_buffer_t* buffers, uint32_t buffer_count);
     * }
     */
    public static int wtf_session_send_datagram(MemorySegment session, MemorySegment buffers, int buffer_count) {
        var mh$ = wtf_session_send_datagram$MH();
        try {
            return (int)mh$.invokeExact(session, buffers, buffer_count);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_create_stream$MH() {
        return RuntimeHelper.requireNonNull(constants$22.const$2,"wtf_session_create_stream");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_session_create_stream(wtf_session_t* session, wtf_stream_type_t type, wtf_stream_t** stream);
     * }
     */
    public static int wtf_session_create_stream(MemorySegment session, int type, MemorySegment stream) {
        var mh$ = wtf_session_create_stream$MH();
        try {
            return (int)mh$.invokeExact(session, type, stream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_get_state$MH() {
        return RuntimeHelper.requireNonNull(constants$22.const$3,"wtf_session_get_state");
    }
    /**
     * {@snippet :
     * wtf_session_state_t wtf_session_get_state(wtf_session_t* session);
     * }
     */
    public static int wtf_session_get_state(MemorySegment session) {
        var mh$ = wtf_session_get_state$MH();
        try {
            return (int)mh$.invokeExact(session);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_get_peer_address$MH() {
        return RuntimeHelper.requireNonNull(constants$22.const$4,"wtf_session_get_peer_address");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_session_get_peer_address(wtf_session_t* session, void* address_buffer, size_t* buffer_size);
     * }
     */
    public static int wtf_session_get_peer_address(MemorySegment session, MemorySegment address_buffer, MemorySegment buffer_size) {
        var mh$ = wtf_session_get_peer_address$MH();
        try {
            return (int)mh$.invokeExact(session, address_buffer, buffer_size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_set_context$MH() {
        return RuntimeHelper.requireNonNull(constants$22.const$6,"wtf_session_set_context");
    }
    /**
     * {@snippet :
     * void wtf_session_set_context(wtf_session_t* session, void* user_context);
     * }
     */
    public static void wtf_session_set_context(MemorySegment session, MemorySegment user_context) {
        var mh$ = wtf_session_set_context$MH();
        try {
            mh$.invokeExact(session, user_context);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_get_context$MH() {
        return RuntimeHelper.requireNonNull(constants$23.const$1,"wtf_session_get_context");
    }
    /**
     * {@snippet :
     * void* wtf_session_get_context(wtf_session_t* session);
     * }
     */
    public static MemorySegment wtf_session_get_context(MemorySegment session) {
        var mh$ = wtf_session_get_context$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(session);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_send$MH() {
        return RuntimeHelper.requireNonNull(constants$23.const$3,"wtf_stream_send");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_send(wtf_stream_t* stream, const wtf_buffer_t* buffers, uint32_t buffer_count, _Bool fin);
     * }
     */
    public static int wtf_stream_send(MemorySegment stream, MemorySegment buffers, int buffer_count, boolean fin) {
        var mh$ = wtf_stream_send$MH();
        try {
            return (int)mh$.invokeExact(stream, buffers, buffer_count, fin);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_close$MH() {
        return RuntimeHelper.requireNonNull(constants$23.const$4,"wtf_stream_close");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_close(wtf_stream_t* stream);
     * }
     */
    public static int wtf_stream_close(MemorySegment stream) {
        var mh$ = wtf_stream_close$MH();
        try {
            return (int)mh$.invokeExact(stream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_abort$MH() {
        return RuntimeHelper.requireNonNull(constants$23.const$5,"wtf_stream_abort");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_abort(wtf_stream_t* stream, uint32_t error_code);
     * }
     */
    public static int wtf_stream_abort(MemorySegment stream, int error_code) {
        var mh$ = wtf_stream_abort$MH();
        try {
            return (int)mh$.invokeExact(stream, error_code);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_get_id$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$0,"wtf_stream_get_id");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_get_id(wtf_stream_t* stream, uint64_t* stream_id);
     * }
     */
    public static int wtf_stream_get_id(MemorySegment stream, MemorySegment stream_id) {
        var mh$ = wtf_stream_get_id$MH();
        try {
            return (int)mh$.invokeExact(stream, stream_id);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_set_callback$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$1,"wtf_stream_set_callback");
    }
    /**
     * {@snippet :
     * void wtf_stream_set_callback(wtf_stream_t* stream, wtf_stream_callback_t callback);
     * }
     */
    public static void wtf_stream_set_callback(MemorySegment stream, MemorySegment callback) {
        var mh$ = wtf_stream_set_callback$MH();
        try {
            mh$.invokeExact(stream, callback);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_set_context$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$2,"wtf_stream_set_context");
    }
    /**
     * {@snippet :
     * void wtf_stream_set_context(wtf_stream_t* stream, void* user_context);
     * }
     */
    public static void wtf_stream_set_context(MemorySegment stream, MemorySegment user_context) {
        var mh$ = wtf_stream_set_context$MH();
        try {
            mh$.invokeExact(stream, user_context);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_get_context$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$3,"wtf_stream_get_context");
    }
    /**
     * {@snippet :
     * void* wtf_stream_get_context(wtf_stream_t* stream);
     * }
     */
    public static MemorySegment wtf_stream_get_context(MemorySegment stream) {
        var mh$ = wtf_stream_get_context$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(stream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_get_type$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$4,"wtf_stream_get_type");
    }
    /**
     * {@snippet :
     * wtf_stream_type_t wtf_stream_get_type(wtf_stream_t* stream);
     * }
     */
    public static int wtf_stream_get_type(MemorySegment stream) {
        var mh$ = wtf_stream_get_type$MH();
        try {
            return (int)mh$.invokeExact(stream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_get_state$MH() {
        return RuntimeHelper.requireNonNull(constants$24.const$5,"wtf_stream_get_state");
    }
    /**
     * {@snippet :
     * wtf_stream_state_t wtf_stream_get_state(wtf_stream_t* stream);
     * }
     */
    public static int wtf_stream_get_state(MemorySegment stream) {
        var mh$ = wtf_stream_get_state$MH();
        try {
            return (int)mh$.invokeExact(stream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_set_priority$MH() {
        return RuntimeHelper.requireNonNull(constants$25.const$1,"wtf_stream_set_priority");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_set_priority(wtf_stream_t* stream, uint16_t priority);
     * }
     */
    public static int wtf_stream_set_priority(MemorySegment stream, short priority) {
        var mh$ = wtf_stream_set_priority$MH();
        try {
            return (int)mh$.invokeExact(stream, priority);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_stream_set_receive_enabled$MH() {
        return RuntimeHelper.requireNonNull(constants$25.const$3,"wtf_stream_set_receive_enabled");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_stream_set_receive_enabled(wtf_stream_t* stream, _Bool enabled);
     * }
     */
    public static int wtf_stream_set_receive_enabled(MemorySegment stream, boolean enabled) {
        var mh$ = wtf_stream_set_receive_enabled$MH();
        try {
            return (int)mh$.invokeExact(stream, enabled);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_session_find_stream_by_id$MH() {
        return RuntimeHelper.requireNonNull(constants$25.const$5,"wtf_session_find_stream_by_id");
    }
    /**
     * {@snippet :
     * wtf_stream_t* wtf_session_find_stream_by_id(wtf_session_t* session, uint64_t stream_id);
     * }
     */
    public static MemorySegment wtf_session_find_stream_by_id(MemorySegment session, long stream_id) {
        var mh$ = wtf_session_find_stream_by_id$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(session, stream_id);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_result_to_string$MH() {
        return RuntimeHelper.requireNonNull(constants$26.const$1,"wtf_result_to_string");
    }
    /**
     * {@snippet :
     * char* wtf_result_to_string(wtf_result_t result);
     * }
     */
    public static MemorySegment wtf_result_to_string(int result) {
        var mh$ = wtf_result_to_string$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(result);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_webtransport_error_to_string$MH() {
        return RuntimeHelper.requireNonNull(constants$26.const$2,"wtf_webtransport_error_to_string");
    }
    /**
     * {@snippet :
     * char* wtf_webtransport_error_to_string(uint32_t error_code);
     * }
     */
    public static MemorySegment wtf_webtransport_error_to_string(int error_code) {
        var mh$ = wtf_webtransport_error_to_string$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(error_code);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_get_error_details$MH() {
        return RuntimeHelper.requireNonNull(constants$26.const$4,"wtf_get_error_details");
    }
    /**
     * {@snippet :
     * wtf_result_t wtf_get_error_details(uint32_t error_code, wtf_error_details_t* details);
     * }
     */
    public static int wtf_get_error_details(int error_code, MemorySegment details) {
        var mh$ = wtf_get_error_details$MH();
        try {
            return (int)mh$.invokeExact(error_code, details);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_is_valid_application_error$MH() {
        return RuntimeHelper.requireNonNull(constants$26.const$6,"wtf_is_valid_application_error");
    }
    /**
     * {@snippet :
     * _Bool wtf_is_valid_application_error(uint32_t error_code);
     * }
     */
    public static boolean wtf_is_valid_application_error(int error_code) {
        var mh$ = wtf_is_valid_application_error$MH();
        try {
            return (boolean)mh$.invokeExact(error_code);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle wtf_http3_error_to_string$MH() {
        return RuntimeHelper.requireNonNull(constants$27.const$1,"wtf_http3_error_to_string");
    }
    /**
     * {@snippet :
     * char* wtf_http3_error_to_string(uint64_t http3_error);
     * }
     */
    public static MemorySegment wtf_http3_error_to_string(long http3_error) {
        var mh$ = wtf_http3_error_to_string$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(http3_error);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * #define NULL 0
     * }
     */
    public static MemorySegment NULL() {
        return constants$27.const$2;
    }
    /**
     * {@snippet :
     * #define _VCRUNTIME_DISABLED_WARNINGS 4514
     * }
     */
    public static int _VCRUNTIME_DISABLED_WARNINGS() {
        return (int)4514L;
    }
    /**
     * {@snippet :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT8_MAX 127
     * }
     */
    public static byte INT8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet :
     * #define INT16_MAX 32767
     * }
     */
    public static short INT16_MAX() {
        return (short)32767L;
    }
    /**
     * {@snippet :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT8_MAX 255
     * }
     */
    public static byte UINT8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet :
     * #define UINT16_MAX 65535
     * }
     */
    public static short UINT16_MAX() {
        return (short)65535L;
    }
    /**
     * {@snippet :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static byte INT_LEAST8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static short INT_LEAST16_MAX() {
        return (short)32767L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static byte UINT_LEAST8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static short UINT_LEAST16_MAX() {
        return (short)65535L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet :
     * #define INT_FAST16_MIN -2147483648
     * }
     */
    public static int INT_FAST16_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT_FAST32_MIN -2147483648
     * }
     */
    public static int INT_FAST32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static byte INT_FAST8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet :
     * #define INT_FAST16_MAX 2147483647
     * }
     */
    public static int INT_FAST16_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT_FAST32_MAX 2147483647
     * }
     */
    public static int INT_FAST32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static byte UINT_FAST8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST16_MAX 4294967295
     * }
     */
    public static int UINT_FAST16_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST32_MAX 4294967295
     * }
     */
    public static int UINT_FAST32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return -1L;
    }
    /**
     * {@snippet :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet :
     * #define WTF_WEBTRANSPORT_APPLICATION_ERROR_BASE 91141958510811
     * }
     */
    public static long WTF_WEBTRANSPORT_APPLICATION_ERROR_BASE() {
        return 91141958510811L;
    }
    /**
     * {@snippet :
     * #define WTF_WEBTRANSPORT_APPLICATION_ERROR_MAX 91146396643682
     * }
     */
    public static long WTF_WEBTRANSPORT_APPLICATION_ERROR_MAX() {
        return 91146396643682L;
    }
}


