// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t error_code;
 *     const char *description;
 *     bool is_application_error;
 *     bool is_transport_error;
 *     bool is_protocol_error;
 * }
 * }
 */
public class wtf_error_details_t {

    wtf_error_details_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        wtf_h.C_INT.withName("error_code"),
        MemoryLayout.paddingLayout(4),
        wtf_h.C_POINTER.withName("description"),
        wtf_h.C_BOOL.withName("is_application_error"),
        wtf_h.C_BOOL.withName("is_transport_error"),
        wtf_h.C_BOOL.withName("is_protocol_error"),
        MemoryLayout.paddingLayout(5)
    ).withName("$anon$285:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt error_code$LAYOUT = (OfInt)$LAYOUT.select(groupElement("error_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t error_code
     * }
     */
    public static final OfInt error_code$layout() {
        return error_code$LAYOUT;
    }

    private static final long error_code$OFFSET = $LAYOUT.byteOffset(groupElement("error_code"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t error_code
     * }
     */
    public static final long error_code$offset() {
        return error_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t error_code
     * }
     */
    public static int error_code(MemorySegment struct) {
        return struct.get(error_code$LAYOUT, error_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t error_code
     * }
     */
    public static void error_code(MemorySegment struct, int fieldValue) {
        struct.set(error_code$LAYOUT, error_code$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final OfBoolean is_application_error$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_application_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_application_error
     * }
     */
    public static final OfBoolean is_application_error$layout() {
        return is_application_error$LAYOUT;
    }

    private static final long is_application_error$OFFSET = $LAYOUT.byteOffset(groupElement("is_application_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_application_error
     * }
     */
    public static final long is_application_error$offset() {
        return is_application_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_application_error
     * }
     */
    public static boolean is_application_error(MemorySegment struct) {
        return struct.get(is_application_error$LAYOUT, is_application_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_application_error
     * }
     */
    public static void is_application_error(MemorySegment struct, boolean fieldValue) {
        struct.set(is_application_error$LAYOUT, is_application_error$OFFSET, fieldValue);
    }

    private static final OfBoolean is_transport_error$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_transport_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_transport_error
     * }
     */
    public static final OfBoolean is_transport_error$layout() {
        return is_transport_error$LAYOUT;
    }

    private static final long is_transport_error$OFFSET = $LAYOUT.byteOffset(groupElement("is_transport_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_transport_error
     * }
     */
    public static final long is_transport_error$offset() {
        return is_transport_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_transport_error
     * }
     */
    public static boolean is_transport_error(MemorySegment struct) {
        return struct.get(is_transport_error$LAYOUT, is_transport_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_transport_error
     * }
     */
    public static void is_transport_error(MemorySegment struct, boolean fieldValue) {
        struct.set(is_transport_error$LAYOUT, is_transport_error$OFFSET, fieldValue);
    }

    private static final OfBoolean is_protocol_error$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_protocol_error"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_protocol_error
     * }
     */
    public static final OfBoolean is_protocol_error$layout() {
        return is_protocol_error$LAYOUT;
    }

    private static final long is_protocol_error$OFFSET = $LAYOUT.byteOffset(groupElement("is_protocol_error"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_protocol_error
     * }
     */
    public static final long is_protocol_error$offset() {
        return is_protocol_error$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_protocol_error
     * }
     */
    public static boolean is_protocol_error(MemorySegment struct) {
        return struct.get(is_protocol_error$LAYOUT, is_protocol_error$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_protocol_error
     * }
     */
    public static void is_protocol_error(MemorySegment struct, boolean fieldValue) {
        struct.set(is_protocol_error$LAYOUT, is_protocol_error$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

