// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     uint32_t error_code;
 *     char* description;
 *     _Bool is_application_error;
 *     _Bool is_transport_error;
 *     _Bool is_protocol_error;
 * };
 * }
 */
public class wtf_error_details_t {

    public static MemoryLayout $LAYOUT() {
        return constants$8.const$5;
    }
    public static VarHandle error_code$VH() {
        return constants$9.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * uint32_t error_code;
     * }
     */
    public static int error_code$get(MemorySegment seg) {
        return (int)constants$9.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * uint32_t error_code;
     * }
     */
    public static void error_code$set(MemorySegment seg, int x) {
        constants$9.const$0.set(seg, x);
    }
    public static int error_code$get(MemorySegment seg, long index) {
        return (int)constants$9.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void error_code$set(MemorySegment seg, long index, int x) {
        constants$9.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle description$VH() {
        return constants$9.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* description;
     * }
     */
    public static MemorySegment description$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$9.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* description;
     * }
     */
    public static void description$set(MemorySegment seg, MemorySegment x) {
        constants$9.const$1.set(seg, x);
    }
    public static MemorySegment description$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$9.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void description$set(MemorySegment seg, long index, MemorySegment x) {
        constants$9.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle is_application_error$VH() {
        return constants$9.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool is_application_error;
     * }
     */
    public static boolean is_application_error$get(MemorySegment seg) {
        return (boolean)constants$9.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool is_application_error;
     * }
     */
    public static void is_application_error$set(MemorySegment seg, boolean x) {
        constants$9.const$2.set(seg, x);
    }
    public static boolean is_application_error$get(MemorySegment seg, long index) {
        return (boolean)constants$9.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void is_application_error$set(MemorySegment seg, long index, boolean x) {
        constants$9.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle is_transport_error$VH() {
        return constants$9.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool is_transport_error;
     * }
     */
    public static boolean is_transport_error$get(MemorySegment seg) {
        return (boolean)constants$9.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool is_transport_error;
     * }
     */
    public static void is_transport_error$set(MemorySegment seg, boolean x) {
        constants$9.const$3.set(seg, x);
    }
    public static boolean is_transport_error$get(MemorySegment seg, long index) {
        return (boolean)constants$9.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void is_transport_error$set(MemorySegment seg, long index, boolean x) {
        constants$9.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle is_protocol_error$VH() {
        return constants$9.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * _Bool is_protocol_error;
     * }
     */
    public static boolean is_protocol_error$get(MemorySegment seg) {
        return (boolean)constants$9.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * _Bool is_protocol_error;
     * }
     */
    public static void is_protocol_error$set(MemorySegment seg, boolean x) {
        constants$9.const$4.set(seg, x);
    }
    public static boolean is_protocol_error$get(MemorySegment seg, long index) {
        return (boolean)constants$9.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void is_protocol_error$set(MemorySegment seg, long index, boolean x) {
        constants$9.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


