// Generated by jextract

package com.structmap.webtransportfast;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     wtf_session_event_type_t type;
 *     wtf_session_t* session;
 *     void* user_context;
 *     union {
 *         struct  disconnected;
 *         struct  stream_opened;
 *         struct  datagram_send_state_changed;
 *         struct  datagram_received;
 *     };
 * };
 * }
 */
public class wtf_session_event_t {

    public static MemoryLayout $LAYOUT() {
        return constants$3.const$5;
    }
    public static VarHandle type$VH() {
        return constants$4.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_session_event_type_t type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$4.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_session_event_type_t type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$4.const$0.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$4.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$4.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle session$VH() {
        return constants$4.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * wtf_session_t* session;
     * }
     */
    public static MemorySegment session$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$4.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * wtf_session_t* session;
     * }
     */
    public static void session$set(MemorySegment seg, MemorySegment x) {
        constants$4.const$1.set(seg, x);
    }
    public static MemorySegment session$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$4.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void session$set(MemorySegment seg, long index, MemorySegment x) {
        constants$4.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle user_context$VH() {
        return constants$4.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static MemorySegment user_context$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$4.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* user_context;
     * }
     */
    public static void user_context$set(MemorySegment seg, MemorySegment x) {
        constants$4.const$2.set(seg, x);
    }
    public static MemorySegment user_context$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$4.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void user_context$set(MemorySegment seg, long index, MemorySegment x) {
        constants$4.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
     * struct {
     *     uint32_t error_code;
     *     char* reason;
     * };
     * }
     */
    public static final class disconnected {

        // Suppresses default constructor, ensuring non-instantiability.
        private disconnected() {}
        public static MemoryLayout $LAYOUT() {
            return constants$4.const$3;
        }
        public static VarHandle error_code$VH() {
            return constants$4.const$4;
        }
        /**
         * Getter for field:
         * {@snippet :
         * uint32_t error_code;
         * }
         */
        public static int error_code$get(MemorySegment seg) {
            return (int)constants$4.const$4.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * uint32_t error_code;
         * }
         */
        public static void error_code$set(MemorySegment seg, int x) {
            constants$4.const$4.set(seg, x);
        }
        public static int error_code$get(MemorySegment seg, long index) {
            return (int)constants$4.const$4.get(seg.asSlice(index*sizeof()));
        }
        public static void error_code$set(MemorySegment seg, long index, int x) {
            constants$4.const$4.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle reason$VH() {
            return constants$4.const$5;
        }
        /**
         * Getter for field:
         * {@snippet :
         * char* reason;
         * }
         */
        public static MemorySegment reason$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$4.const$5.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * char* reason;
         * }
         */
        public static void reason$set(MemorySegment seg, MemorySegment x) {
            constants$4.const$5.set(seg, x);
        }
        public static MemorySegment reason$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$4.const$5.get(seg.asSlice(index*sizeof()));
        }
        public static void reason$set(MemorySegment seg, long index, MemorySegment x) {
            constants$4.const$5.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment disconnected$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    /**
     * {@snippet :
     * struct {
     *     wtf_stream_t* stream;
     *     wtf_stream_type_t stream_type;
     * };
     * }
     */
    public static final class stream_opened {

        // Suppresses default constructor, ensuring non-instantiability.
        private stream_opened() {}
        public static MemoryLayout $LAYOUT() {
            return constants$5.const$0;
        }
        public static VarHandle stream$VH() {
            return constants$5.const$1;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_stream_t* stream;
         * }
         */
        public static MemorySegment stream$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$5.const$1.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_stream_t* stream;
         * }
         */
        public static void stream$set(MemorySegment seg, MemorySegment x) {
            constants$5.const$1.set(seg, x);
        }
        public static MemorySegment stream$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$5.const$1.get(seg.asSlice(index*sizeof()));
        }
        public static void stream$set(MemorySegment seg, long index, MemorySegment x) {
            constants$5.const$1.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle stream_type$VH() {
            return constants$5.const$2;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_stream_type_t stream_type;
         * }
         */
        public static int stream_type$get(MemorySegment seg) {
            return (int)constants$5.const$2.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_stream_type_t stream_type;
         * }
         */
        public static void stream_type$set(MemorySegment seg, int x) {
            constants$5.const$2.set(seg, x);
        }
        public static int stream_type$get(MemorySegment seg, long index) {
            return (int)constants$5.const$2.get(seg.asSlice(index*sizeof()));
        }
        public static void stream_type$set(MemorySegment seg, long index, int x) {
            constants$5.const$2.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment stream_opened$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    /**
     * {@snippet :
     * struct {
     *     wtf_buffer_t* buffers;
     *     uint32_t buffer_count;
     *     wtf_datagram_send_state_t state;
     * };
     * }
     */
    public static final class datagram_send_state_changed {

        // Suppresses default constructor, ensuring non-instantiability.
        private datagram_send_state_changed() {}
        public static MemoryLayout $LAYOUT() {
            return constants$5.const$3;
        }
        public static VarHandle buffers$VH() {
            return constants$5.const$4;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static MemorySegment buffers$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$5.const$4.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_buffer_t* buffers;
         * }
         */
        public static void buffers$set(MemorySegment seg, MemorySegment x) {
            constants$5.const$4.set(seg, x);
        }
        public static MemorySegment buffers$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$5.const$4.get(seg.asSlice(index*sizeof()));
        }
        public static void buffers$set(MemorySegment seg, long index, MemorySegment x) {
            constants$5.const$4.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle buffer_count$VH() {
            return constants$5.const$5;
        }
        /**
         * Getter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static int buffer_count$get(MemorySegment seg) {
            return (int)constants$5.const$5.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * uint32_t buffer_count;
         * }
         */
        public static void buffer_count$set(MemorySegment seg, int x) {
            constants$5.const$5.set(seg, x);
        }
        public static int buffer_count$get(MemorySegment seg, long index) {
            return (int)constants$5.const$5.get(seg.asSlice(index*sizeof()));
        }
        public static void buffer_count$set(MemorySegment seg, long index, int x) {
            constants$5.const$5.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle state$VH() {
            return constants$6.const$0;
        }
        /**
         * Getter for field:
         * {@snippet :
         * wtf_datagram_send_state_t state;
         * }
         */
        public static int state$get(MemorySegment seg) {
            return (int)constants$6.const$0.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * wtf_datagram_send_state_t state;
         * }
         */
        public static void state$set(MemorySegment seg, int x) {
            constants$6.const$0.set(seg, x);
        }
        public static int state$get(MemorySegment seg, long index) {
            return (int)constants$6.const$0.get(seg.asSlice(index*sizeof()));
        }
        public static void state$set(MemorySegment seg, long index, int x) {
            constants$6.const$0.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment datagram_send_state_changed$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    /**
     * {@snippet :
     * struct {
     *     const uint32_t length;
     *     const uint8_t* data;
     * };
     * }
     */
    public static final class datagram_received {

        // Suppresses default constructor, ensuring non-instantiability.
        private datagram_received() {}
        public static MemoryLayout $LAYOUT() {
            return constants$1.const$3;
        }
        public static VarHandle length$VH() {
            return constants$6.const$1;
        }
        /**
         * Getter for field:
         * {@snippet :
         * const uint32_t length;
         * }
         */
        public static int length$get(MemorySegment seg) {
            return (int)constants$6.const$1.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * const uint32_t length;
         * }
         */
        public static void length$set(MemorySegment seg, int x) {
            constants$6.const$1.set(seg, x);
        }
        public static int length$get(MemorySegment seg, long index) {
            return (int)constants$6.const$1.get(seg.asSlice(index*sizeof()));
        }
        public static void length$set(MemorySegment seg, long index, int x) {
            constants$6.const$1.set(seg.asSlice(index*sizeof()), x);
        }
        public static VarHandle data$VH() {
            return constants$6.const$2;
        }
        /**
         * Getter for field:
         * {@snippet :
         * const uint8_t* data;
         * }
         */
        public static MemorySegment data$get(MemorySegment seg) {
            return (java.lang.foreign.MemorySegment)constants$6.const$2.get(seg);
        }
        /**
         * Setter for field:
         * {@snippet :
         * const uint8_t* data;
         * }
         */
        public static void data$set(MemorySegment seg, MemorySegment x) {
            constants$6.const$2.set(seg, x);
        }
        public static MemorySegment data$get(MemorySegment seg, long index) {
            return (java.lang.foreign.MemorySegment)constants$6.const$2.get(seg.asSlice(index*sizeof()));
        }
        public static void data$set(MemorySegment seg, long index, MemorySegment x) {
            constants$6.const$2.set(seg.asSlice(index*sizeof()), x);
        }
        public static long sizeof() { return $LAYOUT().byteSize(); }
        public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
        public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
        }
        public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
    }

    public static MemorySegment datagram_received$slice(MemorySegment seg) {
        return seg.asSlice(24, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


