---
name: package
on:
  workflow_dispatch:
    inputs: {}
  push:
    tags:
      - '*'

jobs:
  build-native:
    strategy:
      matrix:
        include:
          - os: macos-latest
            runtime: osx-arm64
            jextract: https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_macos-aarch64_bin.tar.gz
          - os: macos-15-intel
            runtime: osx-x64
            jextract: https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_macos-x64_bin.tar.gz
          - os: windows-2022
            runtime: win-x64
            jextract: https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_windows-x64_bin.tar.gz
          - os: ubuntu-24.04
            runtime: linux-x64
            jextract: https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_linux-x64_bin.tar.gz
          - os: ubuntu-24.04-arm
            runtime: linux-arm64
            jextract: https://download.java.net/java/early_access/jextract/25/2/openjdk-25-jextract+2-4_linux-aarch64_bin.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: corretto
      # thanks to Nathan for sharing these on GitHub
      # jextract steps from https://github.com/pot/boba/blob/main/.github/workflows/jextract.yml
      - name: Curl jextract
        shell: bash
        run: |
          curl --silent --fail -L ${{ matrix.jextract }} -o jextract.tar.gz
      - name: Extract jextract
        shell: bash
        run: tar -xzf jextract.tar.gz
      - name: Find jextract binary path
        id: jextract_bin
        shell: bash
        run: |
          JEXTRACT_BIN=$(find . -name jextract -type f -path "*/bin/*" | head -n 1)
          echo "path=$JEXTRACT_BIN" >> $GITHUB_OUTPUT
      - name: Chmod jextract
        shell: bash
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: chmod +x ${{ steps.jextract_bin.outputs.path }}
      - name: Configure and build project
        run: |
          cmake -S . -B build
          cmake --build build --config Release
      - name: Parse tag from build context
        uses: olegtarasov/get-tag@v2.1.4
        id: tagVersion
        with:
          tagRegex: "v(.*)"
      - name: Build project and create NuGet package
        run: >
          dotnet pack csharp
          -p:RuntimeTarget=${{ matrix.runtime }}
          -p:PublishVersion=${{ steps.tagVersion.outputs.tag }}
      - name: Upload .NET package to release
        if: steps.tagVersion.outputs.tag != ''
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: csharp/bin/Release/Structmap.WebTransportFast.${{ matrix.runtime }}.${{ steps.tagVersion.outputs.tag }}.nupkg
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
      - name: Run jextract generator
        run: |
          ${{ steps.jextract_bin.outputs.path }} --output java/src --target-package com.structmap.webtransportfast include/wtf.h
      - name: Compile Java to class files
        run: |
          cd java
          javac -d target src/com/structmap/webtransportfast/*
          cd target
          jar --create --file webtransportfast-${{ steps.tagVersion.outputs.tag }}-${{ matrix.runtime }}.jar com/structmap/webtransportfast/*
      - name: Create JAR file
        run: |
          cd java/target
          mkdir -p native/${{ matrix.runtime }}
          cp ../../build/output${{ runner.os == 'Windows' && '/Release' || '' }}/* native/${{ matrix.runtime }}
          jar --create --file webtransportfast-${{ steps.tagVersion.outputs.tag }}-${{ matrix.runtime }}.jar com/structmap/webtransportfast/* native/${{ matrix.runtime }}/*
      - name: Upload JAR artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: java/target/webtransportfast-${{ steps.tagVersion.outputs.tag }}-${{ matrix.runtime }}.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
